### ISSUE TITLE
Asset Library version is outdated and broken

### ISSUE THREAD

**Issue by Kubulambula** [HungryProton/monitor_overlay#7]
While this plugin should be working as it is supposed to, the [Asset Library](https://godotengine.org/asset-library/asset/1280) (from where most of the users would download this plugin) version is really outdated using old API thus making that version broken. 

The asset should be updated to include the latest release so that new users don't encounter an error right away

**Comment by HungryProton** [comment]
True, I forgot this has to be manually done every time.
I've bumped the version number and submitted the changes to the asset lib, I'll close the issue once it's approved.
